# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170702_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=104),
        ),
    ]
